names = ["乔会芳","祁烨","任庆"]
#print(names[0]+"与我共进晚餐吧！")
#print(names[1]+"与我共进晚餐吧！")
#print(names[2]+"与我共进晚餐吧！")
print(names.pop(2)+"不能共进晚餐了")
names.append("门维甲")
#print(names[0]+"与我共进晚餐吧！")
#print(names[1]+"与我共进晚餐吧！")
#print(names[2]+"与我共进晚餐吧！")
print("有一张更大的餐桌，我想再邀请三个人共进晚餐！")
names.insert(0,"丽丽")
names.insert(2,"达达")
names.append("真真")
print(names[0]+"与我共进晚餐吧！")
print(names[1]+"与我共进晚餐吧！")
print(names[2]+"与我共进晚餐吧！")
print(names[3]+"与我共进晚餐吧！")
print(names[4]+"与我共进晚餐吧！")
print(names[5]+"与我共进晚餐吧！")
print("不好意思，餐桌无法及时送达，只能邀请两位共进晚餐！")
print(names.pop()+"非常抱歉，不能与你共进晚餐了。")
print(names.pop()+"非常抱歉，不能与你共进晚餐了。")
print(names.pop()+"非常抱歉，不能与你共进晚餐了。")
print(names.pop()+"非常抱歉，不能与你共进晚餐了。")
print(names[0]+"很荣幸还可以与你共进晚餐！")
print(names[1]+"很荣幸还可以与你共进晚餐！")
print("还有"+str(len(names))+"位嘉宾共进晚餐！")
del names[0]
del names[0]
print(names)
